<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="2" finished="true" name="Test Run: 32" tests="2" total_time="Finished in: 35.72 secs."/>
<test location="C:\Users\user\workspace\python\src\tests\home\login_tests.py" status="fail" test="LoginTests.test_t1invalidLogin" time="21.26">
<stdout><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 56, in logout
    self.nav.navigateToUserSettings()
  File "C:\Users\user\workspace\python\src\pages\home\navigation_page.py", line 31, in navigateToUserSettings
    locatorType="xpath", pollFrequency=1)
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 227, in waitForElement
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 56, in logout
    self.nav.navigateToUserSettings()
  File "C:\Users\user\workspace\python\src\pages\home\navigation_page.py", line 34, in navigateToUserSettings
    locatorType="xpath")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 58, in logout
    locatorType="xpath", pollFrequency=1)
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 227, in waitForElement
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 61, in logout
    locatorType="xpath")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 25, in test_t1invalidLogin
    self.lp.login("test@email.com", "abcabcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
login_tests.py              21 INFO     *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
login_tests.py              22 INFO     test_t1invalidLogin started
login_tests.py              23 INFO     *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
selenium_driver.py         217 INFO     Waiting for maximum :: 10 :: seconds for element to be clickable
selenium_driver.py         226 INFO     Element not appeared on the web page
selenium_driver.py          70 INFO     Element not found with locator: //div[@id='navbar']//li[@class='dropdown'] and  locatorType: xpath
selenium_driver.py         103 INFO     Cannot click on the element with locator: //div[@id='navbar']//li[@class='dropdown'] locatorType: xpath
selenium_driver.py         217 INFO     Waiting for maximum :: 10 :: seconds for element to be clickable
selenium_driver.py         226 INFO     Element not appeared on the web page
selenium_driver.py          70 INFO     Element not found with locator: //div[@id='navbar']//a[@href='/sign_out'] and  locatorType: xpath
selenium_driver.py         103 INFO     Cannot click on the element with locator: //div[@id='navbar']//a[@href='/sign_out'] locatorType: xpath
selenium_driver.py          70 INFO     Element not found with locator: Login and  locatorType: link
selenium_driver.py         103 INFO     Cannot click on the element with locator: Login locatorType: link
selenium_driver.py          70 INFO     Element not found with locator: user_email and  locatorType: id]]></stdout>
<stderr><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 56, in logout
    self.nav.navigateToUserSettings()
  File "C:\Users\user\workspace\python\src\pages\home\navigation_page.py", line 31, in navigateToUserSettings
    locatorType="xpath", pollFrequency=1)
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 227, in waitForElement
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 56, in logout
    self.nav.navigateToUserSettings()
  File "C:\Users\user\workspace\python\src\pages\home\navigation_page.py", line 34, in navigateToUserSettings
    locatorType="xpath")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 58, in logout
    locatorType="xpath", pollFrequency=1)
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 227, in waitForElement
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 24, in test_t1invalidLogin
    #self.lp.logout()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 61, in logout
    locatorType="xpath")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 25, in test_t1invalidLogin
    self.lp.login("test@email.com", "abcabcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
----------------------------- Exceptions -----------------------------
self = <tests.home.login_tests.LoginTests testMethod=test_t1invalidLogin>

    @pytest.mark.run(order=1)
    def test_t1invalidLogin(self):
        self.log.info("*#" * 20)
        self.log.info("test_t1invalidLogin started")
        self.log.info("*#" * 20)
        #self.lp.logout()
>       self.lp.login("test@email.com", "abcabcabc")

tests\home\login_tests.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pages\home\login_page.py:35: in login
    self.clearFields()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.home.login_page.LoginPage object at 0x03437470>

    def clearFields(self):
        emailField = self.getElement(locator=self._email_field)
>       emailField.clear()
E       AttributeError: 'NoneType' object has no attribute 'clear'

pages\home\login_page.py:65: AttributeError]]></stderr>
</test>
<test location="C:\Users\user\workspace\python\src\tests\home\login_tests.py" status="fail" test="LoginTests.test_t2validLogin" time="0.02">
<stdout><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 34, in test_t2validLogin
    self.lp.login("test@email.com", "abcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
login_tests.py              31 INFO     *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
login_tests.py              32 INFO     test_t1invalidLogin started
login_tests.py              33 INFO     *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
selenium_driver.py          70 INFO     Element not found with locator: Login and  locatorType: link
selenium_driver.py         103 INFO     Cannot click on the element with locator: Login locatorType: link
selenium_driver.py          70 INFO     Element not found with locator: user_email and  locatorType: id]]></stdout>
<stderr><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 34, in test_t2validLogin
    self.lp.login("test@email.com", "abcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
----------------------------- Exceptions -----------------------------
self = <tests.home.login_tests.LoginTests testMethod=test_t2validLogin>

    @pytest.mark.run(order=2)
    def test_t2validLogin(self):
        self.log.info("*#" * 20)
        self.log.info("test_t1invalidLogin started")
        self.log.info("*#" * 20)
>       self.lp.login("test@email.com", "abcabc")

tests\home\login_tests.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pages\home\login_page.py:35: in login
    self.clearFields()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.home.login_page.LoginPage object at 0x036AF1F0>

    def clearFields(self):
        emailField = self.getElement(locator=self._email_field)
>       emailField.clear()
E       AttributeError: 'NoneType' object has no attribute 'clear'

pages\home\login_page.py:65: AttributeError]]></stderr>
</test>
<test location="C:\Users\user\workspace\python\src\tests\home\login_tests.py" status="error" test="LoginTests.test_t2validLogin" time="0.02">
<stdout><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 34, in test_t2validLogin
    self.lp.login("test@email.com", "abcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
Running method level tearDown
]]></stdout>
<stderr><![CDATA[  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 254, in <module>
    main()
  File "D:\software\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc\runfiles.py", line 246, in main
    return pytest.main(argv)
  File "C:\Python36-32\lib\site-packages\_pytest\config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 131, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 100, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 138, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\main.py", line 161, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 62, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 158, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 192, in __init__
    self.result = func()
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 178, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python36-32\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\Python36-32\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python36-32\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "C:\Python36-32\lib\site-packages\_pytest\unittest.py", line 174, in runtest
    self._testcase(result=self)
  File "C:\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\user\workspace\python\src\tests\home\login_tests.py", line 34, in test_t2validLogin
    self.lp.login("test@email.com", "abcabc")
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 34, in login
    self.clickLoginLink()
  File "C:\Users\user\workspace\python\src\pages\home\login_page.py", line 22, in clickLoginLink
    self.elementClick(self._login_link, locatorType="link")
  File "C:\Users\user\workspace\python\src\base\selenium_driver.py", line 104, in elementClick
    print_stack()
----------------------------- Exceptions -----------------------------
request = <SubRequest 'oneTimeSetUp' for <TestCaseFunction 'test_t1invalidLogin'>>
browser = None

    @pytest.yield_fixture(scope="session")
    #@pytest.fixture(scope="class")
    def oneTimeSetUp(request, browser):
        print("Running one time setUp")
        wdf = WebDriverFactory(browser)
        driver = wdf.getWebDriverInstance()
        """
        lp = LoginPage(driver)
        lp.login("test@email.com", "abcabc")"""
        test = "test1212"
        '''
        if request.cls is not None:
            request.cls.driver = driver
        #request.cls.test=test
        '''
        yield driver
>       driver.quit()

tests\conftest.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Python36-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py:191: in quit
    RemoteWebDriver.quit(self)
C:\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py:689: in quit
    self.execute(Command.QUIT)
C:\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py:312: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x03437350>
response = {'status': 500, 'value': '{"value":{"error":"session not created","message":"Tried to run command without establishing...      0x4173a7 - <no info>\\n   7:           0x6d38b3 - <no info>\\n   8:     0x7fff884613d2 - BaseThreadInitThunk"}}'}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an error.
    
            :Args:
             - response - The JSON response from the WebDriver server as a dictionary
               object.
    
            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.SessionNotCreatedException: Message: Tried to run command without establishing a connection

C:\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py:242: SessionNotCreatedException]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="python login_tests.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
